### ISSUE TITLE
Fix map on home page

### ISSUE THREAD

**Issue by ZevEisenberg** [ZevEisenberg/swiftfest-site#12]
The map on the home page loads fine when testing locally, but when running on the web, it shows "Oops! Something went wrong.", and in the JS console, it shows this:

```
[Error] Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error
	Pb (js:38:494)
	(anonymous function) (common.js:54:97)
	(anonymous function) (common.js:199:155)
	c (common.js:48:86)
	Global Code (AuthenticationService.Authenticate:1)
```

**Comment by ghost** [comment]
Looks like we need to authenticate to access Maps now?

https://stackoverflow.com/questions/37991340/error-google-maps-api-error-missingkeymaperror

**Comment by ZevEisenberg** [comment]
Whose maps API key should we use? @GiorgioNatili can we get one through the Google Apps account used to host the email addresses? Otherwise, I can make a personal one.

**Comment by ZevEisenberg** [comment]
I thought I had fixed this, but it's not working. I created an API key on my personal Google account, but I'm still getting the same errors as before.

**Comment by ZevEisenberg** [comment]
Thinking this may be easier after we get over to the real domain.

**Comment by ZevEisenberg** [comment]
This was resolved with a combination of moving to the read domain and fixing a bunch of small typos and API misuse issues.
