### ISSUE TITLE
Add email newsletter URL or remove it from the site

### ISSUE THREAD

**Issue by ZevEisenberg** [ZevEisenberg/swiftfest-site#15]
There's a field in _config.yml for an email newsletter form to send a POST to.

**Comment by ghost** [comment]
I'd suggest we remove it. We likely will Tweet our various news?

**Comment by ZevEisenberg** [comment]
Many people (myself included) are not Twitter completionists. When I went to Try! Swift, I loved getting emails over the next few weeks as new videos from the conference became available. I could see many of our attendees feeling the same.

**Comment by ghost** [comment]
Good point. I must say I also enjoy getting updates for conferences that I'm going to, things that make me excited to go. Also in hindsight  building an email list is desirable for communicating future events and speakers.

**Comment by ZevEisenberg** [comment]
I now have access to the MailChimp account, so I should be able to get this wired up.

**Comment by ZevEisenberg** [comment]
I don't have the right permissions yet, but when I do, this is how: https://kb.mailchimp.com/lists/signup-forms/host-your-own-signup-forms

**Comment by ZevEisenberg** [comment]
Newsletter signup is now working as of https://github.com/SwiftFest/swiftfest-site/commit/be861755e1be06fdbb0db1adb38b9f6a26874abd and then https://github.com/SwiftFest/swiftfest-site/commit/b70ded205a8cbb5af98444756b2929ee5b624499
