### ISSUE TITLE
Meta keywords in config contain GDG info

### ISSUE THREAD

**Issue by mdiasdev** [ZevEisenberg/swiftfest-site#23]
**currently:**
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, Lviv"

**expected:**
"swiftfest, swift, apple, iOS, Xcode" etc.

**Comment by ZevEisenberg** [comment]
New keywords:

```
event, swiftfest, boston, programming, swift, apple, ios, macos, tvos, watchos, developers
```

Anyone who wants to modify these, feel free to open a PR.
