### ISSUE TITLE
LinkedIn Profile has a typo

### ISSUE THREAD

**Issue by ghost** [ZevEisenberg/swiftfest-site#25]
I know this isn't directly on the web site but we link to LinkedIn off the web site so if its OK I'll capture any website-related here in order to keep all issues in one place. Is that OK?

On the LinkedIn page there is a small typo in the word "Boston" which is spelled as "Boton", as in:

SwiftFest
Events Services   Boton , Ma

**Comment by ZevEisenberg** [comment]
You might want to put non-website stuff in Trello, unless we're not using that any more. But in either case, @GiorgioNatili is probably the one to make this change.

**Comment by ZevEisenberg** [comment]
Followup: I filed this as a bug on our internal Trello. Going to close this bug.
