### ISSUE TITLE
Captcha error when submitting the Contact Us form

### ISSUE THREAD

**Issue by ghost** [ZevEisenberg/swiftfest-site#26]
I tried to submit the form on the Contact Us page but got the following error even though I had checked the "I'm not a robot" checkbox (see attached screenshots).

Here is the error message:

The reCAPTCHA wasn't entered correctly. Go back and try it again.!

(And if we control the error message maybe we can remove either the period or the exclamation point but not keep both. :-))

Screenshots:

![captcha2](https://user-images.githubusercontent.com/15278837/36068359-b090c79e-0ea1-11e8-9413-80d0deb4feff.png)
![recaptcha](https://user-images.githubusercontent.com/15278837/36068360-b309900a-0ea1-11e8-9f37-094b063ee361.png)

**Comment by ghost** [comment]
Oops Zev this is also the old site.  It can be closed but I don't want to do so since I see it is marked 1.0.

**Comment by ZevEisenberg** [comment]
No worries. 1.0 is just a milestone I created to track everything that has to get done before we can cut over to the real domain. Anything that can wait until after is marked as 1.1.
