### ISSUE TITLE
One of the two links for each sponsor still goes to a demo page

### ISSUE THREAD

**Issue by ghost** [ZevEisenberg/swiftfest-site#28]
Love the sponsor boxes that spin!

Inside the spinning boxes for sponsors are two links to the sponsor web site.  One of the links is for "roles" or "teams", linking to the sponsor job site and all are going to the sponsor's job lists.  

The other link is the headline link for the sponsor name and each one of them goes to this demo:  http://www.showthemes.com/mondree-demo/

Here is a screenshot when I hover my mouse over the Rue La La link. You can see in the bottom left that the link goes to the web site demo:

![sponsorlinks](https://user-images.githubusercontent.com/15278837/36068556-32aacb5e-0ea6-11e8-9e59-63a7211155ec.png)

**Comment by ZevEisenberg** [comment]
This is for the old website. The new website is currently in preview at <https://swiftfest.github.io/swiftfest-site>. We're going to cut over to the new site as soon as all the content is ready for launch. You can track which issues are still left do do by checking out the [1.0 milestone](https://github.com/SwiftFest/swiftfest-site/milestone/1).

**Comment by ZevEisenberg** [comment]
I'm going to close this since it pertains to the old site, but please keep issues coming in for the new site! You can file a new issue [here](https://github.com/SwiftFest/swiftfest-site/issues/new).

**Comment by ghost** [comment]
Oh I'm sorry Zev.  I'm sitting here watching the Olympics and viewing the site.

**Comment by ghost** [comment]
Yes I will keep going on the new site!
