### ISSUE TITLE
Add Cynthia Johnson to Keynote speakers page

### ISSUE THREAD

**Issue by joleary1987** [ZevEisenberg/swiftfest-site#34]
**Cynthia Johnson**

Headshot: https://drive.google.com/file/d/0B7MQ2P9fVqlHYzNYczgxbDJKNFZHY1d1STZGbjZBTkRRSHBJ/view?usp=sharing

**Bio**
Cynthia Johnson is co-founder and CEO at Bell + Ivy, an entrepreneur, speaker, and author.

**Title**
Digital Transformation: Think for Yourself Not About Yourself 

**Abstract**
How can use the communication tools, personal influence, and your own personal network to move the needle for your business and your career? We have all watched fake experts and influencers sit in a seat or find their way to a position that we or someone we know is more qualified for. Who gets heard is not chance, it is a strategy. Your most valuable tool is available and free, it's you.

**Expected Learning Outcome**
What it means to think for yourself and why it matters
How to Understand Your Unique Personal Value Proposition
Tips for leveraging your own influence to drive growth for your career and your company
Having a three-way with a robot: Tips and tricks for navigating your message online
Why it is important to understand the evolution of communication 
How to use game theory to dominate digital communication and growth

**Social Media**
twitter.com/cynthialive
instagram.com/cynthialive
linkedin.com/in/cynjohnson
cynthialive.com
faceboook.com/cynthiajlive
snapchat- @cyninla

**Comment by ZevEisenberg** [comment]
Closed via #37.
