### ISSUE TITLE
Add Bas Broek to speakers page

### ISSUE THREAD

**Issue by joleary1987** [ZevEisenberg/swiftfest-site#35]
**Bas Broek**
Headshot: https://drive.google.com/file/d/0B7MQ2P9fVqlHQURnQS12MGc3c05Jb2NhRDBFZ05iYXFIX0M0/view?usp=sharing

**Bio**
Bas is an iOS & tooling developer working for XING. There, he is working on managing mobile releases on iOS & Android. In his spare time, he is contributing to open source with projects like Swift Weekly Brief, Moya, GitHawk and more.

**Title**
Swift 5 and Beyond: World Domination?

**Abstract**
With Swift 5 on the horizon and Swift 6 development soon in full swing, we take a look at the current state of Swift. What's new in Swift 5, and what can we expect from Swift in the future? Will Swift soon reach World Domination?

**Expected Learning Outcome**
An overview of (what is new in) Swift 5 and what we can expect from Swift in the future, including examples of new features in Swift 5 that can be put in practice immediately.

**Social Media**
Twitter: @basthomas

**Comment by ZevEisenberg** [comment]
Closed via #37.
