### ISSUE TITLE
Add SwiftFest to Repo(s) of conferences

### ISSUE THREAD

**Issue by mdiasdev** [ZevEisenberg/swiftfest-site#38]
Some ingenuitous developers have been maintaining GitHub repos of conferences. We should add SwiftFest to them as soon as the 1.0 milestone is complete (for longer visibility)

https://github.com/Lascorbe/CocoaConferences

**Comment by ZevEisenberg** [comment]
We're in the Lascorbe/CocoaConferences list. Feel free to submit us to others.
