### ISSUE TITLE
Add Alex Bush to Speakers page

### ISSUE THREAD

**Issue by joleary1987** [ZevEisenberg/swiftfest-site#39]
**Alex Bush**

**Headshot**
https://drive.google.com/file/d/0B7MQ2P9fVqlHNGVnYWpkUnBIOU1UbE5YYks0c0tRV0NsM0Nr/view?usp=sharing

**Bio**
Software Consultant, entrepreneur, book author, and podcaster.
Alex is a seasoned iOS consultant who’s been building iOS apps, top to bottom, client to server, over the last 7 years. Alex is an author of The iOS Interview Guide (http://iosinterviewguide.com/) and a co-host at Inside iOS Dev podcast (http://insideiosdev.com/). Currently he's focusing on his consulting work and on leveling up iOS developers by teaching them architecture and design patterns best practices.

**Title**
iOS Interviews Don’t Have To Be Hard

**Abstract**
iOS technologies are rapidly evolving with every WWDC announcement, and it is increasingly challenging for iOS developers to keep up with the features, innovations, and best practices.

It is especially difficult for those preparing for job interviews to navigate the breadth of information available and focus on the most critical topics and skills.

Whether you’re a beginner developer seeking that dream job or a seasoned veteran who is ready for a better one — this talk will prepare you to succeed in your next technical iOS interview.

**Expected Learning Outcome**
This presentation will give an overview of the most important topics and skills covered in a technical iOS interview including:
• typical questions during the various interview stages from phone screens to onsites
• critical components of the iOS tech stack: UI, networking, storage, design patterns, etc
• contemporary best practices 
• best resources for preparing for technical interviews

At the end of this session, the audience will be fully ready to tackle their next iOS interview and know where to go to improve their skills and knowledge in specific topics.

**Social Media**
blog: http://m.smartcloud.io/
twitter: https://twitter.com/alex_v_bush
linkedin: https://www.linkedin.com/in/alexvbush/
podcast: http://insideiosdev.com/

**Comment by ZevEisenberg** [comment]
Closed via #37.
