### ISSUE TITLE
Giorgio's staff profile

### ISSUE THREAD

**Issue by GiorgioNatili** [ZevEisenberg/swiftfest-site#4]
- Giorgio Natili
- Twitter: https://twitter.com/giorgionatili
- Linkedin: https://www.linkedin.com/in/giorgionatili

![headshoot](https://user-images.githubusercontent.com/1223504/35953775-0df18982-0c3b-11e8-9e6f-e4c934258dc6.jpg)

**Comment by ZevEisenberg** [comment]
Closed via 9f33a36671d9c7b648699711564308525baa3953
