### ISSUE TITLE
Add Agnes Vasarhelyi to Speakers Page

### ISSUE THREAD

**Issue by joleary1987** [ZevEisenberg/swiftfest-site#45]
Photo: https://drive.google.com/file/d/1Ga5xzlVcPpUsuOl3qEjfgaUDbNJVs4P9/view?usp=sharing

Bio: "Agnes is a Hungarian living in San Francisco, hard at work bringing the high tech revolution to the fashion industry at Topology Eyewear. Meetup and conference organizer in her previous life in Budapest, now busy building premium user experiences on iOS, learning about graphics programming, and hiking the mountains of California in the meantime."

Social Twitter: @vasarhelyia

Title: 
The Simple Layout of a Complex Interface
 
Abstract:
Understanding Auto Layout is your best chance to write UI code you can be proud of. Its power often underestimated, its features easily misused, I find it overall less appreciated than it could be, if more widely understood.
 
This talk is aiming to show how relying heavily on Auto Layout makes you move faster and be more confident writing UI code. Working with the safe area, showing off custom UILayoutGuides and making use of the controversal UIStackViews, we will walk through the simple code of a more complex interface together.
 
Attendees can expect to learn:
How to express layout fast and simple, without touching Interface Builder
How Auto Layout helps to reduce state in your views / view controllers
Why the safe area is great and how to rely on it without knowing what device your code is running on
When to use custom UILayoutGuides and how they help to avoid using numeric values all around
UIStackViews: why they are great, but controversial. How to work with stack views in scrollable layouts

**Comment by vasarhelyia** [comment]
hey @joleary1987 seems like the handle links to my GitHub, not my Twitter.

**Comment by joleary1987** [comment]
Sorry about that @vasarhelyia - I didn't mean to @ you in GitHub, it'll show up as a Twitter Handle on the actual SwiftFest site when we add it here: http://swiftfest.io/

Thanks!
