### ISSUE TITLE
Beth staff stuff

### ISSUE THREAD

**Issue by emezias** [ZevEisenberg/swiftfest-site#5]
Elizabeth Mezias
www.linkedin.com/in/bethmezias
https://twitter.com/bethmezias aka @bethmezias 
![festprofile](https://user-images.githubusercontent.com/830129/36035703-b135b85c-0d85-11e8-9225-c0ef7aa735d8.png)

**Comment by ZevEisenberg** [comment]
Closed via 9f33a36671d9c7b648699711564308525baa3953
