### ISSUE TITLE
Code of Conduct link in the footer is broken

### ISSUE THREAD

**Issue by ghost** [ZevEisenberg/swiftfest-site#59]
The link to Code of Conduct in the top navigation is working and links to:

http://swiftfest.io/code-of-conduct/

But the link to Code of Conduct in the footer is broken and throwing a 404 because it links to:

http://swiftfest.io/conduct/

We just need to update the footer link to be correct.

**Comment by ZevEisenberg** [comment]
Fixed in fda57b7
