### ISSUE TITLE
Update Alexandrea Mellen as MC

### ISSUE THREAD

**Issue by ghost** [ZevEisenberg/swiftfest-site#70]
bio: Alexandrea Mellen is a technical content marketer at callstats.io. She has developed multiple iOS applications for her company, Terrapin Computing, as well as several freelance projects.

**Comment by ZevEisenberg** [comment]
Thanks! Closed via https://github.com/SwiftFest/swiftfest-site/commit/df6210268b4c644fa45c7971b840545def043ee2
