### ISSUE TITLE
Add podcasts as supporters

### ISSUE THREAD

**Issue by mdiasdev** [ZevEisenberg/swiftfest-site#75]
Linked are the logos for each podcast

**Fireside Swift**
https://is1-ssl.mzstatic.com/image/thumb/Music128/v4/b4/6f/4b/b46f4b60-e467-925e-6932-371282ebfcd7/source/1024x1024bb.jpg

**Swift Coders**
https://deow9bq0xqvbj.cloudfront.net/image-logo/953625/SwiftCodersArtwork.png

**The Learn Swift Podcast**
https://is2-ssl.mzstatic.com/image/thumb/Music128/v4/f4/d9/eb/f4d9ebbb-d500-aa89-5e89-5c3ec12d3d30/source/1024x1024bb.jpg

**Swift Craft**
https://is1-ssl.mzstatic.com/image/thumb/Music128/v4/03/f5/38/03f5385a-0a8c-95f5-bcd0-3a784d8235be/source/1024x1024bb.jpg

**Comment by mdiasdev** [comment]
Also adding in:
LEARN SWIFT {CITY}

They don't have a logo per se. can we add the above formatted text?

**Comment by ZevEisenberg** [comment]
A logo would be nice, even if it were just text as an image.

**Comment by mdiasdev** [comment]
I'll see what I can draw up

**Comment by ZevEisenberg** [comment]
I can help too. And I guess I can use the NSCoder logo from the Boston meetup site. No idea where it came from. Maybe @earnshavian made it when he ran the group?

**Comment by mdiasdev** [comment]
![learn swift city](https://user-images.githubusercontent.com/1463672/39558201-9c052cc2-4e5a-11e8-8e3f-ace79c530c36.png)

I threw this together based on https://swiftcoders.org/2017/03/07/learn-swift-la/ let me know what you think

**Comment by ZevEisenberg** [comment]
Works for me! I’ll have a PR up soon.

**Comment by ZevEisenberg** [comment]
@mdiasdev would you mind posting the original file you used to make that? I may tweak the font and spacing.

**Comment by mdiasdev** [comment]
I can when I get home... I made it in Affinity Photo, is there a preferred file type?

**Comment by ZevEisenberg** [comment]
Can you swing a .psd?

**Comment by ZevEisenberg** [comment]
Actually, never mind, I have everything I need: the `{•}` element, the font (montserrat), and the colors. I'll take it from here 😉

**Comment by ZevEisenberg** [comment]
@mdiasdev what do you think about this? It uses the same font as the website, and I think it will work better at a small size on the site.

![image](https://user-images.githubusercontent.com/464574/39584360-3a8b63ec-4ec0-11e8-9b82-a47fb8e81819.png)

**Comment by mdiasdev** [comment]
gorgeous! I spent 30min trying to find a font for it, thank you!

**Comment by ZevEisenberg** [comment]
Right Click → Inspect Element on the SwiftCoders web page 😉
