### ISSUE TITLE
tighten up space at the top of the page

### ISSUE THREAD

**Issue by emezias** [ZevEisenberg/swiftfest-site#8]
There is a large empty swath of color from the template at the top of the site pages and it forces the user to immediately scroll. Please tighten up that spacing. 

For example - on the new speakers page there is "Team" in white on blue immediately followed by a large "About Us". Two titles is one too many. Pick one. That big block of menus, titles, and the empty color field - all text - that pushes the interesting images offscreen.

**Comment by ZevEisenberg** [comment]
I think the original template had some background images instead of the big blue splotch, but I'm all for making it smaller instead of filling in a useless stock photo 👍

**Comment by ZevEisenberg** [comment]
We now have header images on all pages.
