### ISSUE TITLE
Schedule Adjustments

### ISSUE THREAD

**Issue by mdiasdev** [ZevEisenberg/swiftfest-site#95]
**Shorten Day 1**
We are concerned about people getting tired at the end of the conference. **Day 1 should end at 6pm** thus dropping the 6-7 slot

**First Sessions on Day 2 Should Change to Keynote**
This should push all sessions in track 1 and 2 down one slot

**Comment by ZevEisenberg** [comment]
Also dropping out 4pm-5pm slots on day 2

**Comment by ZevEisenberg** [comment]
@mdiasdev @GiorgioNatili what should we do with the final workshop on day 2? If we remove the slot after it, there's nowhere for it to continue.

**Comment by ZevEisenberg** [comment]
Never mind, I figured it out by shifting the sessions around. Please test locally before merging my PR to make sure it makes sense!

**Comment by GiorgioNatili** [comment]
Tested locally, LGTM.
